eureka:
  client:
    register-with-eureka: false

server:
  port: 8080

spring:
  application:
    name: msvc-gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: courses
              uri: http://localhost:9090
              predicates:
                - Path=/api/course/**
            - id: students
              uri: lb://msvc-student
              predicates:
                - Path=/api/student/**
